package ReverseModule;


/**
* ReverseModule/Reverse.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Reverse.idl
* Wednesday, 6 May, 2026 10:31:48 PM IST
*/

public interface Reverse extends ReverseOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Reverse
