package ReverseModule;


/**
* ReverseModule/ReverseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Reverse.idl
* Wednesday, 6 May, 2026 10:40:07 PM IST
*/

public interface ReverseOperations 
{
  String uppercase_string (String str);
} // interface ReverseOperations
